### ISSUE TITLE
Check Broken Extension

### ISSUE THREAD

**Issue by morange** [lochmueller/autoloader#198]
Hello Tim,
I did a scan in the past few days in Admin Tools under Upgrade > Check for Broken Extensions, I got the following notices.
I use ddev version v1.21.1, web server Apache, PHP 8.0 or PHP 8.1
<img width="438" alt="Bildschirmfoto 2022-08-23 um 12 26 33" src="https://user-images.githubusercontent.com/8067083/189079358-df408a40-8c90-4f0e-a456-d14358df0773.png">
Many thanks, Steffen

**Comment by lochmueller** [comment]
Hey @okmiim ,
Hey @morange 

I moved this issue to EXT:autoloader.
The behaviour is strange. The problem is, that $GLOBALS['TCA'] do not exists in the ExtensionManagementUtility::addStaticFile call, but the variable should exists, because we are in the ext_tables.php loading process :-/ If there are any ideas... please add more information.

Regards,
Tim

**Comment by sypets** [comment]
I noticed the problem too now. I did not do extensive testing in the Frontend with 8.1 yet so I do not know if this might be affected as well.

The "Check for Broken Extensions" reports problems in these extensions (which all seem to be related to autoloader):

* autoloader
* calendarize
* calendarize_address
* calendarize_news


The problem is always that some entry in` $GLOBALS['TCA']` is not initialized and is caused by calling `\HDNET\Autoloader\Loader::extTables` in `ext_tables.php` (which calls `ExtensionManagementUtility` functions at some point).

I think **ExtensionManagementUtility::addStaticFile()** should not be called from` ext_tables.php`, as pointed out in the documentation.

But there are also some other ExtensionsManageUtility functions which are being called from ext_tables.php.

The documentation:

> calling ExtensionManagementUtility::addStaticFile() as this might break the frontend. They should go in Configuration/TCA/Overrides/sys_template.php

* main: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ExtTables.html
* 11.5: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/FileStructure/ExtTables.html

----

Versions:

* PHP 8.1
* TYPO3 11.5.21
* autoloader: 7.3.9

**Comment by sypets** [comment]
I add, how I dumped the exception messages as this might be convenient:

UpgradeController::extensionCompatTesterLoadExtTablesAction

```
try {
+                $packageKey = $package->getPackageKey();
                $this->extensionCompatTesterLoadExtTablesForExtension($package);
            } catch (\Throwable $e) {
                $brokenExtensions[] = [
                    'name' => $package->getPackageKey(),
                    'isProtected' => $package->isProtected(),
                ];
+                if ($packageKey === 'calendarize') {
+                   throw $e;
+                }
            }
```

By catching the exception, the core obscures the exception dumps. This way, you can cause a log entry in the error log specifically for an extension.

And I did get different function calls and missing arrays for calendarize and autoloader ...

**Comment by sypets** [comment]
Exception for "autoloader":

* PHP Warning: Undefined array key "sys_template" (in `$GLOBALS['TCA']['sys_template']`)
* when calling: `ExtensionManagementUtility::addStaticFile`


```
PHP Warning: Undefined array key "sys_template" in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1360

Fri, 23 Dec 2022 10:15:36 +0100 [CRITICAL] request="0a46f3fb43e89" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: BE): TYPO3\CMS\Core\Error\Exception, code #1476107295, file /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Error/ErrorHandler.php, line 137: PHP Warning: Undefined array key "sys_template" in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1360- Exception: PHP Warning: Undefined array key "sys_template" in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1360, in file /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Error/ErrorHandler.php:137 - {"mode":"WEB","application_mode":"BE","exception_class":"TYPO3\\CMS\\Core\\Error\\Exception","exception_code":1476107295,"file":"/var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Error/ErrorHandler.php","line":137,"message":"PHP Warning: Undefined array key \"sys_template\" in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1360","request_url":"https://site11.uol.de/typo3/install.php?install[controller]=upgrade&install[context]=backend","exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Undefined array key \"sys_template\" in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1360 in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Error/ErrorHandler.php:137
Stack trace:
#0 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php(1360): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError()
#1 /var/www/site-uol11/htdocs/typo3conf/ext/autoloader/Classes/Loader/StaticTyposcript.php(59): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::addStaticFile()
#2 /var/www/site-uol11/htdocs/typo3conf/ext/autoloader/Classes/Loader.php(100): HDNET\\Autoloader\\Loader\\StaticTyposcript->loadExtensionTables()
#3 /var/www/site-uol11/htdocs/typo3conf/ext/autoloader/Classes/Loader.php(73): HDNET\\Autoloader\\Loader->loadExtTables()
#4 /var/www/site-uol11/htdocs/typo3conf/ext/autoloader/ext_tables.php(15): HDNET\\Autoloader\\Loader::extTables()
#5 /var/www/site-uol11/htdocs/typo3/sysext/install/Classes/Controller/UpgradeController.php(1348): require('...')
#6 /var/www/site-uol11/htdocs/typo3/sysext/install/Classes/Controller/UpgradeController.php(584): TYPO3\\CMS\\Install\\Controller\\UpgradeController->extensionCompatTesterLoadExtTablesForExtension()
#7 /var/www/site-uol11/htdocs/typo3/sysext/install/Classes/Middleware/Maintenance.php(259): TYPO3\\CMS\\Install\\Controller\\UpgradeController->extensionCompatTesterLoadExtTablesAction()
#8 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(121): TYPO3\\CMS\\Install\\Middleware\\Maintenance->process()
#9 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#10 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\
ormalizedParamsAttribute->process()
#11 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(78): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#12 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/AbstractApplication.php(86): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle()
#13 /var/www/site-uol11/htdocs/typo3/sysext/install/Classes/Http/Application.php(52): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle()
#14 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/AbstractApplication.php(100): TYPO3\\CMS\\Install\\Http\\Application->handle()
#15 /var/www/site-uol11/htdocs/typo3/install.php(99): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()
#16 /var/www/site-uol11/htdocs/typo3/install.php(100): {closure}()
#17 {main}"}

```

**Comment by sypets** [comment]
Exception for "calendarize":

* Undefined array key "columns" (in $GLOBALS['TCA']['tt_content'], this only contains `types` for some reason)
* in **ExtensionManagementUtility::addPiFlexFormValue**

```
Fri, 23 Dec 2022 10:30:00 +0100 [CRITICAL] request="7d80282d30378" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: BE): TYPO3\CMS\Core\Error\Exception, code #1476107295, file /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Error/ErrorHandler.php, line 137: PHP Warning: Undefined array key "columns" in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1254- Exception: PHP Warning: Undefined array key "columns" in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1254, in file /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Error/ErrorHandler.php:137 - {"mode":"WEB","application_mode":"BE","exception_class":"TYPO3\\CMS\\Core\\Error\\Exception","exception_code":1476107295,"file":"/var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Error/ErrorHandler.php","line":137,"message":"PHP Warning: Undefined array key \"columns\" in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1254","request_url":"https://site11.uol.de/typo3/install.php?install[controller]=upgrade&install[context]=backend","exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Undefined array key \"columns\" in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1254 in /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Error/ErrorHandler.php:137
Stack trace:
#0 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php(1254): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError()
#1 /var/www/site-uol11/htdocs/typo3conf/ext/autoloader/Classes/Loader/FlexForms.php(66): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::addPiFlexFormValue()
#2 /var/www/site-uol11/htdocs/typo3conf/ext/autoloader/Classes/Loader.php(100): HDNET\\Autoloader\\Loader\\FlexForms->loadExtensionTables()
#3 /var/www/site-uol11/htdocs/typo3conf/ext/autoloader/Classes/Loader.php(73): HDNET\\Autoloader\\Loader->loadExtTables()
#4 /var/www/site-uol11/htdocs/typo3conf/ext/calendarize/ext_tables.php(9): HDNET\\Autoloader\\Loader::extTables()
#5 /var/www/site-uol11/htdocs/typo3conf/ext/calendarize/ext_tables.php(39): TYPO3\\CMS\\Install\\Controller\\UpgradeController->{closure}()
#6 /var/www/site-uol11/htdocs/typo3/sysext/install/Classes/Controller/UpgradeController.php(1352): require('...')
#7 /var/www/site-uol11/htdocs/typo3/sysext/install/Classes/Controller/UpgradeController.php(585): TYPO3\\CMS\\Install\\Controller\\UpgradeController->extensionCompatTesterLoadExtTablesForExtension()
#8 /var/www/site-uol11/htdocs/typo3/sysext/install/Classes/Middleware/Maintenance.php(259): TYPO3\\CMS\\Install\\Controller\\UpgradeController->extensionCompatTesterLoadExtTablesAction()
#9 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(121): TYPO3\\CMS\\Install\\Middleware\\Maintenance->process()
#10 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#11 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\
ormalizedParamsAttribute->process()
#12 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(78): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#13 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/AbstractApplication.php(86): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle()
#14 /var/www/site-uol11/htdocs/typo3/sysext/install/Classes/Http/Application.php(52): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle()
#15 /var/www/site-uol11/htdocs/typo3/sysext/core/Classes/Http/AbstractApplication.php(100): TYPO3\\CMS\\Install\\Http\\Application->handle()
#16 /var/www/site-uol11/htdocs/typo3/install.php(99): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()
#17 /var/www/site-uol11/htdocs/typo3/install.php(100): {closure}()
#18 {main}"}


```

**Comment by lochmueller** [comment]
Hey @okmiim , @sypets & @morange 
this problem is fixed in the current master branch: https://github.com/lochmueller/autoloader/commit/fcab32ca8ee4d08a3ff736a35a9d372c6dff83db
There is a new interface that can be implemented in the Loaders and the related Loaders are executed in the "ModelUtility::getTcaOverrideInformation" execution in the Overrides-TCA-Files. So the two problem functions are not called in ext_tables.php anymore.
Regards,
TIm
